name: pre-merge optimizations

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
    - name: Prettier Formatting
      uses: creyD/prettier_action@v4.2
      with:
          prettier_options: --write **/*.{js,ts,md}
